
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Novo Evento 2",
    "date": "2024-06-29T14:00:00.00",
    "description": "Descricao do evento",
    "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "Novo evento 999",
    "date": "2024-06-29T14:00:00.00",
    "description": "Descricao do evento",
    "price": 100
}

###
DELETE http://localhost:3000/events/{{eventId}}
